### ISSUE TITLE
requirements for contributed data

### ISSUE THREAD

**Issue by derhuerst** [trainline-eu/stations#357]
Friends of mine and me have scraped a lot of data from German & European HAFAS endpoints. We collected a couple of hundred thousand stations. We mainly use endpoints that are not officially released for public usage but are can just be queried. Would you be interested in taking PRs with this data?

**Comment by derhuerst** [comment]
@juliuste @highsource

**Comment by espadrine** [comment]
@derhuerst Thank you for your offer and enthusiasm!

We are worried that this might break HaCon's terms and conditions, however. Sorry, but we'll have to decline.

**Comment by highsource** [comment]
I'm not quite sure why are HaCon TOC relevant. Do you mean ToC of transport companies?

**Comment by espadrine** [comment]
Does the contract under which you have access to HAFAS allow you to publicize its contents under ODbL?

**Comment by derhuerst** [comment]
I won't speak for @highsource, but I don't have any license. It just query their endpoint.

**Comment by espadrine** [comment]
@derhuerst What endpoint is it? I'd expect all endpoints to be subjected to terms of service.

**Comment by derhuerst** [comment]
There are lots of endpoints on the internet you can query without signing any terms. It may be the case that I do in fact violate them, but I've never seen any TOCs and query the endpoint every day.
