### ISSUE TITLE
How to add new stations?

### ISSUE THREAD

**Issue by severak** [trainline-eu/stations#360]
Is there any procedure how to add new stations?

For example - I needed to add [Čelákovice](https://en.wikipedia.org/wiki/%C4%8Cel%C3%A1kovice) to my local database and I am obliged to share this improvement by license.

**Comment by severak** [comment]
BTW - I just acquired station list of Czech railways and I am allowed to republish it under ODbL.

**Comment by chtitux** [comment]
Just add them at the end of the file, and create a merge request.

If you do have the authorization, please indicate it in your merge request.
