### ISSUE TITLE
Saint-Sébastien

### ISSUE THREAD

**Issue by Fabrice-Orgogozo** [trainline-eu/stations#734]
line 5043 of stations.csv, it should be "Donostia-San Sebastián", not "San Sebastián-Donostia".
This is the official name of the city [cf. https://es.wikipedia.org/wiki/San_Sebasti%C3%A1n]
See https://www.openstreetmap.org/?mlat=43.317668&mlon=-1.976781#map=19/43.31767/-1.97678
or a picture of the train station on Google maps: https://goo.gl/maps/faCkPxUSHdR2
Fabrice Orgogozo.

**Comment by ConscritNeuneu** [comment]
ADIF calls the train station San Sebastián – Donostia

http://www.adif.es/es_ES/infraestructuras/estaciones/11511/informacion_000031.shtml

and it matches the displays on the platforms

https://goo.gl/maps/nLsVG7526xC2

We won't change ourselves but we are willing to accept a pull request.
