### ISSUE TITLE
Activate Milano Forlanini for Trenitalia ?

### ISSUE THREAD

**Issue by mgalibert** [trainline-eu/stations#86]
It looks like this station is used as a stop for regional trains.
However the station is unknown in Trenitalia and Deutsche Bahn systems.

https://it.wikipedia.org/wiki/Stazione_di_Milano_Forlanini

**Comment by benedettolevi** [comment]
It is actually used only for Suburban Trenord trains. 
http://www.trenord.it/media/1439332/mappalinees_01pmag2015.pdf.pdf

**Comment by mgalibert** [comment]
The station has been added in the meantime.
